// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./../components/HeaderSearch/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Screenfull: typeof import('./../components/Screenfull/index.vue')['default']
    SelectColor: typeof import('./../components/ThemeSelect/components/selectColor.vue')['default']
    Src: typeof import('./../components/SvgIcon/src/index.vue')['default']
    ThemeSelect: typeof import('./../components/ThemeSelect/index.vue')['default']
  }
}

export { }
